### PR TITLE
Update connect-session-sequelize

### PR DESCRIPTION
**Pull request by FlorSousa**
I added a function that allows to manually update the session, I did it because I was having some errors in relation to saving to the db after some change in the req.session

**example usage**:
```
//get the cookie and id
    let cookie = req.session.cookie //used in creation of data
    let id = req.session.id //used for search session

    //here's is defined the new field in data
    let newfield = 'Hi, i am a test'

    //here's is a object with data
    let data = {
        cookie,
        newfield

    }

    //call the function ForcedUpdate(r eq.session.id , {})
    Storage.ForcedUpdate(id, data)
```

### CODE REVIEW

**Comment by FlorSousa** [comment]
Sorry I didn't quite understand what went wrong here, I'm a jr

**Comment by mweibel** [comment]
I don't think this should be needed and IMO would be the wrong place to put it. 
`connect-session-sequelize` is defined by the interface [express-session](https://github.com/expressjs/session) exposes. We should not add more than that IMO. 

What you describe sounds more like either a bug or a user error. Could you please open an issue instead with an example on what you're trying to do?

**Comment by FlorSousa** [comment]
@mweibel Hello, good afternoon, my failure to explain what I meant. Basically the "touch ()" of express-session is only called when something is sent to the client (res), this means that if I create a post route to just receive the data and add it to a session this will be done, however, as your code depends on "touch ()" to insert in the database those data saved in the session will not be saved in the database, so when I try to access them by another route the result will be undefined. Below is a very simple code example and a print of the debug console :


```
app.get('/a', (req, res) => {
    req.session.new = "new value"
    console.log('route /a')
    res.send('Hi') //using the touch()
        //save the value
})

app.get('/', (req, res) => {
    console.log('route /')
    console.log(req.session.new + "---> outup")
        //seeing the saved value
})

app.get('/b', (req, res) => {
    console.log('route /b')
    req.session.newtwo = "other value"
        //saves the value but not start touch()

})

app.get('/c', (req, res) => {
    console.log("route /c")
    console.log(req.session.newtwo + "----> output")
        //and result undefined
})
```



debug

as you can see on route / b the INSERT INTO was not done

**Comment by mweibel** [comment]
@FlorSousa why wouldn't you want to send a response in response to a GET request? at least in the minimum you'd probably send a [204 No Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) - which might touch the session too. 
In any case - if this is still an issue, I'd rather open an issue with express-session to get this discussed instead of fixing it in a specific session store.

**Pull request closed without merging**
