### PR TITLE
Making fn optional for destroy() #21.

### LINKED ISSUE #21: Session destroy not removing entry from DB.
Session get destroy successfully but and not removing entry form DB. Its giving error:

	Unhandled rejection TypeError: undefined is not a function
	    at errorDestroying (/home/costrategix/Node/project/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:157:11)
	    at tryCatcher (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
	    at Promise._settlePromiseFromHandler (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
	    at Promise._settlePromiseAt (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
	    at Promise._settlePromises (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
	    at Async._drainQueue (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
	    at Async._drainQueues (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
	    at Async.drainQueues (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
	    at process._tickCallback (node.js:415:13)

### PR DESCRIPTION
**Pull request by jakeorr**
for #21

### CODE REVIEW

**Comment by deepak-manwal** [comment]
@jakeorr Checking function undefined is not solution. I am saving session in DB but its always creating entry in `Session` table, everything is working fine. But its not clearing session at the time of Log Out.

**Comment by mweibel** [comment]
should I merge this already or not yet?

**Comment by jakeorr** [comment]
Hold off for now, there might be more to include.

**Comment by jakeorr** [comment]
Hey @mweibel this can be merged. The change is good regardless of what happens with the referenced issue. Any other additions for the issue can be done as separate PR's if you're happy with that.

**Comment by mweibel** [comment]
version 2.3.1 has been published

**Pull request merged**
