### PR TITLE
Add options to sync

### PR DESCRIPTION
**Pull request by hadrien-f**
Sequelize sync model function can take options as argument.
We can use options also while using connect-session-sequelize

### CODE REVIEW

**Comment by mweibel** [comment]
Thanks for your contribution. What kind of options are possible for `sync` and why do you need options there?

Also, could you please adjust `index.d.ts` and the README as well?

**Comment by hadrien-f** [comment]
I will add information about the options parameter in the Readme.
The options are detailed here : [https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-sync](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-sync)
My use case for this is to specify a specific logging function but other use case are also enable by this.

**Comment by AlanMorel** [comment]
These changes look good to me

**Comment by mweibel** [comment]
I'd need also an adjustment to the Typescript typings file `index.d.ts` :)

**Comment by mweibel** [comment]
sorry, misclicked.. :sweat_smile:

**Comment by mweibel** [comment]
Version 7.1.0 has been published on NPM

**Pull request merged**
