### PR TITLE
Promote `stopExpiringSessions` to public API method

### LINKED ISSUE #65: Expose `stopExpiringSessions` so that Mocha 4 can exit gracefully
This bit me hard today. Bear with me while I explain the context.

Mocha 4 has a breaking change. As the [v4 release notes](https://github.com/mochajs/mocha/releases/tag/v4.0.0) indicate:

> By default, Mocha will no longer force the process to exit once all tests complete. This means any test code (or code under test) which would normally prevent node from exiting will do so when run in Mocha. Supply the `--exit` flag to revert to pre-v4.0.0 behavior.

Possible solutions:

- supply `--exit` (easiest, masks true problem)
- downgrade to mocha v3 (easy, masks true problem, regressive)
- use global `after` to cleanup whatever is hanging (best but sometimes hardest)

Following advice from [this Mocha issue](https://github.com/mochajs/mocha/issues/3044) and using a debugging trick from [this gist](https://gist.github.com/boneskull/7fe75b63d613fa940db7ec990a5f5843), I discovered that an undocumented interval was being created by [this line of `connect-session-sequelize`](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L152). Thankfully, an undocumented internal implementation method at [this line](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L158) meant that the following cleanup hook works:

```js
// in app module

app.set('sessionStore', sessionStore)
```

```js
// in spec

after('clean up resources', () => {
  console.log('stopping session store expiration interval')
  app.get('sessionStore').stopExpiringSessions()
})
```

Now my Mocha tests exit gracefully, because `connect-session-sequelize` isn't keeping the process alive indefinitely. Arguably, `connect-session-sequelize` ought to have a public API method to tell it to stop persisting the process so that it can be properly cleaned up in similar cases.

### PR DESCRIPTION
**Pull request by glebec**
Closes #65.

Includes tests.

### CODE REVIEW

**Comment by mweibel** [comment]
Thanks, that's released as version 5.1.0 now. 👍

**Comment by glebec** [comment]
Cool. By the way, I found out that the project uses Standard style and that Travis fails the build if linting errors only through the PR submission. A combo of the following can prevent that sort of late failure:

* Include eslint & standard config as dev deps of the project (with a project-specific eslintrc file)
* Use [husky](https://github.com/typicode/husky) to easily create git hooks which run the linter before pushing (or whatever other git action you may prefer)

I am not promoting this comment to full issue as you may very well be happy with your current workflow, but the above can help prevent collaborators from experiencing build failures.

**Comment by mweibel** [comment]
`npm run lint` will run `standard` on the codebase. Maybe the only issue is that this is not documented enough?
Or, the other option is, you're using an IDE which can detect eslint if there's an `.eslintrc` file and adding that would resolve the issue?

**Comment by glebec** [comment]
> `npm run lint` will run `standard` on the codebase. Maybe the only issue is that this is not documented enough?

Yes, I ran this locally after discovering that linting was part of the Travis build, I am merely suggesting that it be more obvious that the linter needs to pass. This can be partly solved through documentation (e.g. [contributing / PR / issue templates](https://github.com/glebec/springboard/tree/master/.github)), but it can also be automated through git hooks. Neither is necessary, it was obvious once the Travis build failed what was happening, these other options are just luxuries that make the contribution process smoother.

> Or, the other option is, you're using an IDE which can detect eslint if there's an .eslintrc file and adding that would resolve the issue?

Yep, a local (project-specific) eslintrc would let editors pick up on the linting rules, again allowing for early warning instead of late failure.

**Pull request merged**
