### PR TITLE
Refactor everything to use promises more promise like

### PR DESCRIPTION
**Pull request by BridgeAR**

### CODE REVIEW

**Comment by mweibel** [comment]
Thanks! This looks good to me. @jakeorr?
Two minor things:
1. should we use `asCallback` instead of `nodeify` instead? It's the same function but the [new in bluebird 3.0](http://bluebirdjs.com/docs/new-in-bluebird-3.html) tells me that 
> `.nodeify` is now better known as `.asCallback`

2. should we add a test to check that the traditional node.js callback style still works? Making sure that the API didn't change basicly.

**Comment by BridgeAR** [comment]
@mweibel the reason why I choose not to use `asCallback` is that there are likely still quite a few people using an older bluebird version. This is especially important for people who use a shrinkwrap file where different libraries may not require different bluebird versions. And there are still a lot of libraries that require bluebird 2.x.

To test that the lib works with callbacks (it has to, since express-sessions works like that) I could just revert the test changes.

**Comment by BridgeAR** [comment]
I changed nodeify to asCallback and updated the sequelize minimum requirement to 2.1 (it is the first release that matches the bluebird release that contains asCallback).

I also changed the tests back to callbacks and realized that three tests seemed to not have worked properly earlier. Or should destroy error out in any of those cases? I guess not?

**Comment by jakeorr** [comment]
Nice, this change looks good to me :+1: Weird about the tests. I went back and they were not failing as they should have been. You're right that `.destroy()` should not be returning an error. This version tests as expected; asserting that destroy does return an error fails as it should. Good fixing.

**Comment by mweibel** [comment]
:+1: thanks! indeed weird about the tests, but this seems more correct.
I'll merge and then release a new version

**Comment by mweibel** [comment]
Version 3.0.0 has been published on npm :) Thanks again!

**Pull request merged**
